Add retry mechanism to restore writes
aerospike/backup-go pull request #114
Opened 2024-08-15 09:01 UTC by korotkov-aerospike

2024-08-15 14:30 UTC, korotkov-aerospike commented
make sense to use same RetryPolicy object on backup

2024-08-18 13:33 UTC, filkeith requested changes

2024-08-18 13:33 UTC, filkeith commented on io/aerospike/record_batch_writer.go
> +		} else if !shouldRetry(err) {
May be avoid `else if ` if not necessary. Like:

```go
if !shouldRetry(err) {
    return fmt.Errorf("non-retryable error on restore: %w", err)
}
```

then

```go
if isNilOrAcceptableError(err) {
    rw.operationBuffer = rw.processAndFilterOperations()
        if len(rw.operationBuffer) == 0 {
             return nil // All operations succeeded
         }
}
```

2024-08-18 13:33 UTC, filkeith commented on io/aerospike/record_writer.go
> +	retryPolicy *models.RetryPolicy
May be I missing smth, but didn't *a.WritePolicy.MaxRetry do the same? or we want to retry only on certain errors?

2024-08-18 15:28 UTC, korotkov-aerospike commented on io/aerospike/record_batch_writer.go
> +		} else if !shouldRetry(err) {
unfortunately, it's not that simple, acceptable errors should not be retried.

2024-08-18 15:43 UTC, korotkov-aerospike commented on io/aerospike/record_writer.go
> +	retryPolicy *models.RetryPolicy
yes, not all errors are retryable. But more important, we want to avoid having too much connections to aerospike, so when we do our own retry mechanism, we don't hold connection while sleeping.

2024-08-18 16:29 UTC, filkeith approved these changes

2024-08-18 16:46 UTC, reugn approved these changes

2024-08-20 12:11 UTC, merged